name: Publish to PyPi

on:
  workflow_call:
    inputs:
      version:
        description: 'Type of version update (major, minor, patch)'
        required: true
        default: 'patch'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build bump2version
        
      - name: Bump version
        run: |
          bump2version ${{ github.event.inputs.version }}

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m build
          twine upload dist/*
